---

- name: Install apache
  hosts: all
  become: true
  tasks: 

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
      update_cache: yes
    when:  ansible_os_family=="Debian"
  - name: start apache2 daemon
    service:
        name: apache2
        state: started
        enabled: yes 
    when:  ansible_os_family=="Debian"    
